name: cluster_capes_venv
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - nltk
  - ipykernel
 