name: cluster_capes_venv
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - unidecode
  - nltk
  - python-levenshtein
  - pyarrow
  - fastparquet
  - ipykernel